### PR TITLE
Added Response Constants

### PR DESCRIPTION
**Pull request by pappyJ**

### CODE REVIEW

**Comment by Dishebh** [comment]
Thank you so much for the PR! Although, I don't see a particular use case to use the constants instead of hard-coded values here, as we do not as such require many response status codes (apart from a few).

**Comment by pappyJ** [comment]
Yeah Sure the response object has many unused ones but i din't think a few byte of string would not have much perfomance effect on the project .... but i can strip the unused ones if you insist sir

**Comment by Dishebh** [comment]
Why consume some extra bytes of memory when we can already make do with whatever we have on our platter already 😄. We won't be needing, at least for now. If in future there comes a requirement for this, I'll let you know. :)

**Comment by pappyJ** [comment]
Create more issues to give us more things to work on

**Pull request closed without merging**
