### PR TITLE
Adding various security features issue #168

### PR DESCRIPTION
**Pull request by udaymittal7**
Added rate limiter to receive 100 requests per hour from a particular IP address.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.

Please review and if any changes required let me know.
Thank you.

For issue #168

### CODE REVIEW

**Comment by udaymittal7** [comment]
I can't understand this check fail. Please help.

**Comment by Dishebh** [comment]
IMG-20210316-WA0002

These are lint errors. You can try running 
`npm run lint` to see if it fixes the issue, or else you can address each error separately and resolve it. Let me know if you face any difficulty in either way.

**Comment by udaymittal7** [comment]
By running this command it is showing me this kind of very long error. I don't know how to fix it. Please help.
image

**Comment by udaymittal7** [comment]
I tried removing errors manually in app.js file. Please check.

**Comment by Dishebh** [comment]
Great work @udaymittal7

**Comment by udaymittal7** [comment]
Thank you @Dishebh. Please add the relevant tags here too for the scores to reflect. Thank you.

**Pull request merged**
